### ISSUE TITLE
type definitions don't work for tuple types

### ISSUE THREAD

**Issue by ajafff** [sindresorhus/arrify#10]
```ts
declare let tuple: [number, string];

const arrified = arrify(tuple);
arrified.push(1);
arrified[0] = 'foo'
```

Since tuples are arrays, they are returned as is. The type declarations however widen the type to a regular (mutable) array type.  Both mutations above should not be allowed.

**Comment by BendingBender** [comment]
This is not correct. Tuples are mutable by default. You can't push to a tuple but you can mutate values inside.

**Comment by BendingBender** [comment]
Any suggestions on how to fix this?
