### ISSUE TITLE
Doesn't work with array-like objects

### ISSUE THREAD

**Issue by fregante** [sindresorhus/arrify#2]
This sounded interesting but my main use case would be transforming results from `document.querySelector(All)` to arrays, and that doesn't work (meaning that they end up in a single-element array, always)

Can this be modified to work with array-like objects?

**Comment by sindresorhus** [comment]
It is intentionally strict. APIs should IMHO just accept Arrays. If you need to use an array like object it should be up to you to convert it. What if a user actually want the array-like object to be an element in the array. With ES6 this will be easy with `Array.from()`.

**Comment by fregante** [comment]
Gotcha. Array.from looks pretty good though, I'll be using that one a lot
