### ISSUE TITLE
Support for multiple arguments

### ISSUE THREAD

**Issue by jvandemo** [sindresorhus/arrify#3]
Would it make sense to include support for multiple arguments?

``` javascript
var arrify = require('arrify');
arrify('unicorn', 'unicorn');
```

and if so, would it then best return:

``` javascript
//=> ['unicorn', 'unicorn']
```

or

``` javascript
//=> [['unicorn'], ['unicorn']]
```

or is the module intentionally strict to only support one argument?

Thanks!

**Comment by sindresorhus** [comment]
What's the use-case?

**Comment by jvandemo** [comment]
You're right, I was just wondering about it and not really thinking of an actual (useful) use-case.

Hit me on the head with a hammer! :hammer:

Sorry for taking your time @sindresorhus!
